name: Supabase Write to avoid dormancy cron

on:
  schedule:
    - cron: '0 0 * * *' # Runs every Sunday at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install supabase

      - name: Run Supabase script
        env:
          SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
        run: python ./scripts/supabase_cron.py
